# Generated by Django 5.0.4 on 2024-06-30 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
