# Generated by Django 5.0.4 on 2024-06-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
