# Generated by Django 5.0.4 on 2024-06-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_remove_news_likes_alter_comment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
