# Generated by Django 5.0.4 on 2024-06-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_news_likes_news_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='news',
            name='video_url',
        ),
    ]
